server:
  port: 8004

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.mariadb.jdbc.Driver            # mariadb驱动包
    url: jdbc:mariadb://localhost:3306/testb5f4?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Admin123
  cloud:
    zookeeper:
      connect-string: 81.68.245.135:2181

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.shou.entities    # 所有Entity别名类所在包
